apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx-container
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /var/log/nginx
          name: data
      volumes:
      - hostPath:
          path: /var/log/storage/nginx
          type: ""
        name: data
